name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Strip
        uses: tarmil/strip-markdown-html@3142ddd42026adf66e6114217b47b370ce22a4a2
        with:
          input-path: in.md
          output-path: output/out.md
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
